# Generated by Django 6.0.6 on 2026-06-12 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SobraMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('unidade', models.CharField(choices=[('g', 'Grama(s)'), ('kg', 'Quilo(s)'), ('mg', 'Miligrama(s)'), ('cm', 'Centímetro(s)'), ('m', 'Metro(s)'), ('mm', 'Milímetro(s)'), ('l', 'Litro(s)'), ('ml', 'Mililitro(s)'), ('un', 'Unidade(s)')], default='un', max_length=10)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Doado', 'Doado')], default='Disponível', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('justificativa', models.TextField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_dispositivos/')),
                ('sobra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='materiais.sobramaterial')),
            ],
        ),
    ]
