# Generated by Django 5.2.7 on 2025-10-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SobraMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('doado', 'Doado')], default='Disponível', max_length=20)),
            ],
        ),
    ]
