# Generated by Django 5.2.7 on 2025-10-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobramaterial',
            name='unidade',
            field=models.CharField(choices=[('g', 'Grama(s)'), ('kg', 'Quilo(s)'), ('mg', 'Miligrama(s)'), ('cm', 'Centímetro(s)'), ('m', 'Metro(s)'), ('mm', 'Milímetro(s)'), ('l', 'Litro(s)'), ('ml', 'Mililitro(s)'), ('un', 'Unidade(s)')], default='un', max_length=10),
        ),
        migrations.AlterField(
            model_name='sobramaterial',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Doado', 'Doado')], default='Disponível', max_length=20),
        ),
    ]
