# Generated by Django 5.2.7 on 2025-10-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_sobramaterial_unidade_alter_sobramaterial_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='sobras/')),
            ],
        ),
        migrations.AddField(
            model_name='sobramaterial',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='sobras/'),
        ),
    ]
