# Generated by Django 5.2.7 on 2025-10-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_sobra_sobramaterial_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sobra',
        ),
        migrations.RemoveField(
            model_name='sobramaterial',
            name='imagem',
        ),
    ]
