# Generated by Django 5.2.7 on 2025-10-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_delete_sobra_remove_sobramaterial_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobramaterial',
            name='imagem_dispositivo',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_dispositivos/'),
        ),
    ]
