# Generated by Django 5.2.7 on 2025-10-22 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0005_sobramaterial_imagem_dispositivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_dispositivos/')),
                ('sobra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='materiais.sobramaterial')),
            ],
        ),
    ]
